### ISSUE TITLE
nflog.c: nflog_unbind_pf called instead of nflog_bind_pf

### ISSUE THREAD

**Issue by mpuzio** [cloudflare/pmtud#1]
Just a quick issue I noticed while browsing the code. This would easily go undetected, because it appears that nflog_bind_pf() ignores second parameter and always binds for both AF_INET and AF_INET6. Thus "nflog_bind_pf(n->h, AF_INET6)" a few lines further hides the bug.

``` diff
--- src/nflog.c.orig    2016-01-07 12:53:09.000000000 -0600
+++ src/nflog.c 2016-01-07 12:53:39.933119500 -0600
@@ -81,7 +81,7 @@
         PFATAL("nflog_unbind_pf(AF_INET6)");
     }

-    r = nflog_unbind_pf(n->h, AF_INET);
+    r = nflog_bind_pf(n->h, AF_INET);
     if (r < 0) {
         PFATAL("nflog_bind_pf(AF_INET)");
     }
```

**Comment by majek** [comment]
Awesome report. Thanks!
