### ISSUE TITLE
Issues when running with pcap_next_ex

### ISSUE THREAD

**Issue by martintopholm** [cloudflare/pmtud#2]
We were considering running pmtud, but needed to expand it to cover L3
use cases. During this work I discovered that handle_packet wasn't called
for every received packet. This appears to be the case for v0.6.

I suspected this was related to the interaction between the nonblocking
pcap interface and uevent system. So I tried to run the main loop as
pcap_loop instead which resulted in all packets beeing handled (and
ratelimited).

My test setup comprise a workstation (client) with curl, a router (r1)
running Debian, a subnet br1 with two Busybox nodes (n1, n2), and a
subnet br2 with two more Busybox nodes (n3, n4). The link from r1 to
client is restricted to mtu 600. See also pmtud-test-setup.svg.

For this case a service address is routed to n2, unless it is tcp in
which case it is routed to n1 using fwmarks. The client retrieves PNG
file from the service address, which triggers unreachable from r1 to n2.

The http transfer was successful, but tcpdump from n2 shows 5
received icmp-unreach while only one line of "10.0.4.1 transmitting
mtu=600 sport=-1". See case1-tcpdumps.txt.

When I modified the source to use pcap_loop all packets are handled
(in case2 it is 5 of them 2 forwarded and 3 rate limited). See
case2-tcpdumps.txt.

[pmtud-test-setup.pdf](https://github.com/cloudflare/pmtud/files/87392/pmtud-test-setup.pdf)
[case1-tcpdumps.txt](https://github.com/cloudflare/pmtud/files/87393/case1-tcpdumps.txt)
[case2-tcpdumps.txt](https://github.com/cloudflare/pmtud/files/87394/case2-tcpdumps.txt)

**Comment by majek** [comment]
> I suspected this was related to the interaction between the nonblocking pcap interface and uevent system

Well, uevent is just "select" loop, so we don't do anything fancy. Get file descriptor from pcap and wait on it using select(). Pmtud ships and compiles with fresh version libpcap, Can you try compiling it against a systems one? or maybe downgrade / upgrade?

When possible I prefer to use select() on file descriptors as opposed to use glorified blocking api's like pcap_loop.

Also, beware that pmtud does rate limiting and will try not to broadcast too many packets.

**Comment by martintopholm** [comment]
On Tue, 12 Jan 2016, Marek wrote:

> [...] Can you try compiling it against a systems one? or maybe downgrade / upgrade?

Arch Linux doesn't appear to have .a files of the pcap library. But I have tried switching deps/libpcap to 1.7.4 (same as systems' version), 1.6.2, and 1.5.3.

Result are the same. pmtud only passes judgement ("transmitting" or "ratelimited") on some of the packets the host receives.

> When possible I prefer to use select() on file descriptors as opposed to use glorified blocking api's like pcap_loop.

Yes, I prefer eventprogramming over threading as well and I wouldn't suggest replacing uevent with the loop. It was merely an observation that pcap_loop interface did get all the packets.

> Also, beware that pmtud does rate limiting and will try not to broadcast too many packets.

I'm fairly certain that it isn't caused by ratelimiting as verbose output doesn't say "Ratelimited". In case2 with pcap_loop some packets are ratelimited and some are transmitted, but in contrast to case1 all packets receives judgement.

**Comment by majek** [comment]
Okay, what do you propose? Is there a way we could reproduce this? Do you think the problem is with pmtud or libpcap?

**Comment by martintopholm** [comment]
I was hoping that others were seeing this problem as well. I don't know what the solution is.

In my opinion my setup doesn't do anything special (as described in the first post) except that is a QEMU environment. It would appear that Linux easily generates 6 icmp-unreach-needfrag packets (seen in [case1-tcpdumps.txt](https://github.com/cloudflare/pmtud/files/87393/case1-tcpdumps.txt)). I would guess you could see the problem by sending those (within the second) and running pmtud with -vv

How do you pcap test setup look? What kind of flows do you test with?

I think the problem is in libpcap. As far as I can see pcap_next_ex isn't returning all packets.

I think I will try a few different kernel versions, to see if that changes anything.

**Comment by majek** [comment]
Okay, could you maybe create two simple programs with the same bpf filter as we use in pmtud, one using pcap_loop, another using pcap_next_ex, and see if you can reproduce the issue without al the framework we added here?

Alternatively I can suggest avoiding using libpcap and maybe use NFLOG.

**Comment by martintopholm** [comment]
The following commit (included in Linux v3.19) appears to have fixed the issue.

```
commit da413eec729dae5dcb150e2eb34c5e7e5e4e1b49 (HEAD, refs/bisect/new)
Author: Dan Collins
Date:   Fri Dec 19 16:49:25 2014 +1300

packet: Fixed TPACKET V3 to signal poll when block is closed rather than every packet

Make TPACKET_V3 signal poll when block is closed rather than for every
packet. Side effect is that poll will be signaled when block retire
timer expires which didn't previously happen. Issue was visible when
sending packets at a very low frequency such that all blocks are retired
before packets are received by TPACKET_V3. This caused avoidable packet
loss. The fix ensures that the signal is sent when blocks are closed
which covers the normal path where the block is filled as well as the
path where the timer expires. The case where a block is filled without
moving to the next block (ie. all blocks are full) will still cause poll
to be signaled.
```

**Comment by majek** [comment]
Wow, awesome finiding. Correct me if I'm wrong:

TPACKET is a packet_mmap capturing interface [1], whcih allows userspace program to get packets with less copying of data. For some reason in kernel.... 3.18? it was broken and didn't cause poll to be singalled.

[1] https://www.kernel.org/doc/Documentation/networking/packet_mmap.txt

**Comment by martintopholm** [comment]
Yes, that is how I understand it. It seems like version 3 of the TPACKET API that was broken from at least v3.16 untill v3.19.
